apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: arcaplay-xyz-tls
spec:
  secretName: arcaplay-xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: arcaplay.xyz
  dnsNames:
    - arcaplay.xyz
    - www.arcaplay.xyz
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - arcaplay.xyz
          - www.arcaplay.xyz